# Generated by Django 4.0.6 on 2022-07-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(max_length=5000, unique=True),
        ),
    ]
